---
title: "{{< fa circle-question >}} Frequently asked questions"
---

### What if I get sick during the semester?
Please follow the [UBC CAMPUS RULES & GUIDANCE DOCUMENTS](https://srs.ubc.ca/health-safety/safety-programs/communicable-disease-prevention-framework/).

**DO NOT COME TO CLASS**.

You can complete all of your assignments electronically (and remotely).

We will drop the lowest worksheet grade from the semester.

### What if I get sick right before an exam?

**DO NOT COME TO THE EXAM**.
Your instructor will make alternate arrangements if you get sick right before/during a exam. Please contact your instructor as far in advance as possible, and fill out an academic concession form (available on the Canvas page).

### What is the structure of the class?
Each week will have the following pattern:

Your instructor will release pre-lecture reading material on Monday
In class, your instructor will begin with a brief lecture to introduce a new concept. Then you’ll do a worksheet to practice the concept.
In tutorial, the TAs will run a tutorial to reinforce the concept we learned in lecture. You’ll do another worksheet to practice the concept. The tutorial worksheets are generally harder than the lecture worksheets.
There will be one midterm, one final exam, and one group project.

### How do I submit a worksheet?

- Worksheets: You must complete all of your worksheets on our JupyterHub server. Once you are done working, go to `File -> Save and Checkpoint`, and make sure the checkpoint is “a few seconds ago” at the top of your screen. We will show you how to do this in class. You don’t need to click “submit” anywhere – our server will automatically take a snapshot of your assignment at the due date. Make sure you do not move / rename your assignment from where it originally was on the server.

- Case studies / other assignments: You will submit these on Canvas.

### How do I get my assignment regraded?

Please see the course syllabus.

### Where do I find due dates?

All due dates are listed on Canvas.

### What if I registered late? When are things due?

- If you registered after an assignment was due, then that assignment will be due exactly 1 week after your registration date & time.

- If you registered before an assignment was due, the assignment from that class is due at the normal time.

### I’m going to be late / absent for a class! Who do I notify?

Your instructor does not need to be informed when you’ll be absent from a regular class. We understand that, from time to time, you will not be able to attend the lecture sessions. However, since iClicker participation is a part of your grade, regular attendance is encouraged to ensure you can fully engage with the material and earn participation marks.

If you are going to be absent from an exam, you need to fill out a self-declared concession form in a timely manner prior to the exam. See the course policies on the syllabus for details.

### Do I satisfy the math requirement for this class?
The prerequisite for this course is DSCI 100. 

### How do I get help in the course?

- Office Hours: The TAs and I will hold office hours at various times throughout the week via Zoom/in-person. See Canvas for times/locations. I encourage you to ask questions about the worksheets, case studies or any other questions about the course material.

- Piazza Discussion Board: You can post on the Piazza Discussion board to ask your questions about the course material. You can also help your classmates by answering their questions.

- Email: For questions about the course material, please post your questions on Piazza. If you have personal questions that do not pertain to the course material itself you can email the course instructor (please see syllabus for emails). Please note: Most instructors only respond to emails Monday to Friday, and try their best to answer you as promptly as possible. However, given the large class size it may take a few days to respond.

### How do I do well in this course?

Most importantly: complete and understand the worksheets. These are intended to help you learn the concepts so you’ll do well on the case studies and exams. The worksheets tend to be a bit easier and provide more guidance. 

For lecture worksheets, you can collaborate with your peers (this is encouraged!) as discussing the material while you work on it will help you learn. But you are not allowed to simply copy another student’s work. That is plagiarism, which is expressly forbidden in the course policy.

Time management is very important in this course. There are regular assessments every week to keep you on track, but we move quickly and cover a lot of ground. 

Take an active role in the learning community that we will build together. Ask questions on Piazza when you have them, and try to answer each others’ questions when you can.

> Attribution: These FAQ have been adapted from [DSCI 100's FAQ](https://github.com/UBC-DSCI/dsci-100-student/blob/master/FAQ.md).

